=== mikesaidani/L2JDatapack/L2J_DataPack_BETA/dist/game/data/xsd/faenor.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="Event">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Droplist">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="AllDrop">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="Items" />
											<xs:attribute type="xs:string" name="Count" />
											<xs:attribute type="xs:string" name="Chance" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="Message">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute type="xs:string" name="Type" />
								<xs:attribute type="xs:string" name="Msg" />
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
				<xs:element name="Npc">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Condition">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Inventory">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="Items" />
														<xs:attribute type="xs:byte" name="Count" />
														<xs:attribute type="xs:string" name="Operation" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Take">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Item">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="Items" />
														<xs:attribute type="xs:byte" name="Count" />
														<xs:attribute type="xs:string" name="Type" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Give">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Item" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:short" name="ItemID" use="optional" />
														<xs:attribute type="xs:byte" name="Count" use="optional" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="SystemMessage">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="Msg" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:short" name="ID" />
					</xs:complexType>
				</xs:element>
				<xs:element name="EventEnd">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Take">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Item">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:string" name="ItemID" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute type="xs:string" name="From" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="ID" />
			<xs:attribute type="xs:string" name="Active" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mikesaidani/L2JDatapack/L2J_DataPack_BETA/dist/game/data/faenor/Valentines.xml
<Event ID="Valentines Event" Active="14 Feb 2005-16 Feb 2005" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xsd/faenor.xsd">
	<Droplist>
		<AllDrop Items="4209-4217" Count="1,1" Chance="5%" />
	</Droplist>
	<Message Type="OnJoin" Msg="Valentine's Event:\nCollect all 9 Hearts Blocks to recieve a reward!!\n(Quest Item.. All monster's have a chance to drop.)" />
	<Npc ID="12371">
		<Condition>
			<Inventory Items="4209-4217" Count="1" Operation=">=" />
		</Condition>
		<Take>
			<Item Items="4209-4217" Count="1" Type="OfEach" />
		</Take>
		<Give>
			<Item ItemID="4625" Count="1" />
			<Item ItemID="1540" Count="10" />
			<Item ItemID="728" Count="10" />
		</Give>
		<SystemMessage Msg="Congratulations. Receive your prize." />
	</Npc>
	<EventEnd>
		<Take From="AllPlayers">
			<Item ItemID="4209-4217" />
		</Take>
	</EventEnd>
</Event>
