=== mikesaidani/L2JDatapack/L2J_DataPack_BETA/dist/game/data/xsd/optionsData.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="option" maxOccurs="unbounded" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="for" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="add" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:attribute type="xs:string" name="order" use="required" />
												<xs:attribute type="xs:string" name="stat" use="required" />
												<xs:attribute type="xs:float" name="val" use="required" />
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="active_skill" minOccurs="0">
								<xs:complexType>
									<xs:attribute type="xs:integer" name="id" use="required" />
									<xs:attribute type="xs:integer" name="level" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="passive_skill" minOccurs="0">
								<xs:complexType>
									<xs:attribute type="xs:integer" name="id" use="required" />
									<xs:attribute type="xs:integer" name="level" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="attack_skill" minOccurs="0">
								<xs:complexType>
									<xs:attribute type="xs:integer" name="id" use="required" />
									<xs:attribute type="xs:integer" name="level" use="required" />
									<xs:attribute type="xs:float" name="chance" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="critical_skill" minOccurs="0">
								<xs:complexType>
									<xs:attribute type="xs:integer" name="id" use="required" />
									<xs:attribute type="xs:integer" name="level" use="required" />
									<xs:attribute type="xs:float" name="chance" use="required" />
								</xs:complexType>
							</xs:element>
							<xs:element name="magic_skill" minOccurs="0">
								<xs:complexType>
									<xs:attribute type="xs:integer" name="id" use="required" />
									<xs:attribute type="xs:integer" name="level" use="required" />
									<xs:attribute type="xs:float" name="chance" use="required" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:integer" name="id" use="required" />
						<xs:attribute type="xs:string" name="name" use="required" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mikesaidani/L2JDatapack/L2J_DataPack_BETA/dist/game/data/stats/options/24900-24999.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/optionsData.xsd">
	<option id="24900" name="o_july_shirt_attr_49">
		<!-- Increases Resistance to Water, Fire, Wind, Earth, Holy, and Dark attributes by 50 each. -->
		<for>
			<add order="0x40" stat="windRes" val="50" />
			<add order="0x40" stat="fireRes" val="50" />
			<add order="0x40" stat="earthRes" val="50" />
			<add order="0x40" stat="waterRes" val="50" />
			<add order="0x40" stat="holyRes" val="50" />
			<add order="0x40" stat="darkRes" val="50" />
		</for>
	</option>
	<option id="24901" name="o_july_shirt_attr_50">
		<!-- Increases Resistance to Water, Fire, Wind, Earth, Holy, and Dark attributes by 50 each. -->
		<for>
			<add order="0x40" stat="windRes" val="50" />
			<add order="0x40" stat="fireRes" val="50" />
			<add order="0x40" stat="earthRes" val="50" />
			<add order="0x40" stat="waterRes" val="50" />
			<add order="0x40" stat="holyRes" val="50" />
			<add order="0x40" stat="darkRes" val="50" />
		</for>
	</option>
	<option id="24902" name="o_july_shirt_stat_4">
		<!-- CON +1 -->
		<for>
			<add order="0x40" stat="CON" val="1" />
		</for>
	</option>
	<option id="24903" name="o_july_shirt_stat_5">
		<!-- CON +1. MEN +1. -->
		<for>
			<add order="0x40" stat="STR" val="0" />
			<add order="0x40" stat="INT" val="0" />
			<add order="0x40" stat="CON" val="1" />
			<add order="0x40" stat="DEX" val="1" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24904" name="o_july_shirt_stat_6">
		<!-- INT +1. STR +1. CON +1. MEN +1. -->
		<for>
			<add order="0x40" stat="STR" val="1" />
			<add order="0x40" stat="INT" val="1" />
			<add order="0x40" stat="CON" val="1" />
			<add order="0x40" stat="DEX" val="1" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24905" name="o_july_shirt_stat_7">
		<!-- INT +1. STR +1. CON +2. MEN +1. -->
		<for>
			<add order="0x40" stat="STR" val="1" />
			<add order="0x40" stat="INT" val="1" />
			<add order="0x40" stat="CON" val="2" />
			<add order="0x40" stat="DEX" val="1" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24906" name="o_july_shirt_stat_8">
		<!-- INT +1. STR +1. CON +2. MEN +2. -->
		<for>
			<add order="0x40" stat="STR" val="1" />
			<add order="0x40" stat="INT" val="1" />
			<add order="0x40" stat="CON" val="2" />
			<add order="0x40" stat="DEX" val="2" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24907" name="o_july_shirt_stat_9">
		<!-- INT +2. STR +2. CON +2. MEN +2. -->
		<for>
			<add order="0x40" stat="STR" val="2" />
			<add order="0x40" stat="INT" val="2" />
			<add order="0x40" stat="CON" val="2" />
			<add order="0x40" stat="DEX" val="2" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24908" name="o_july_shirt_stat_10">
		<!-- INT +2. STR +2. CON +3. MEN +2. -->
		<for>
			<add order="0x40" stat="STR" val="2" />
			<add order="0x40" stat="INT" val="2" />
			<add order="0x40" stat="CON" val="3" />
			<add order="0x40" stat="DEX" val="2" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24909" name="o_july_shirt_stat_11">
		<!-- INT +2. STR +2. CON +3. MEN +3. -->
		<for>
			<add order="0x40" stat="STR" val="2" />
			<add order="0x40" stat="INT" val="2" />
			<add order="0x40" stat="CON" val="3" />
			<add order="0x40" stat="DEX" val="3" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24910" name="o_july_shirt_stat_12">
		<!-- INT +3. STR +3. CON +3. MEN +3. -->
		<for>
			<add order="0x40" stat="STR" val="3" />
			<add order="0x40" stat="INT" val="3" />
			<add order="0x40" stat="CON" val="3" />
			<add order="0x40" stat="DEX" val="3" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24911" name="o_july_shirt_stat_13">
		<!-- INT +3. STR +3. CON +4. MEN +3. -->
		<for>
			<add order="0x40" stat="STR" val="3" />
			<add order="0x40" stat="INT" val="3" />
			<add order="0x40" stat="CON" val="4" />
			<add order="0x40" stat="DEX" val="3" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24912" name="o_july_shirt_stat_14">
		<!-- INT +3. STR +3. CON +4. MEN +4. -->
		<for>
			<add order="0x40" stat="STR" val="3" />
			<add order="0x40" stat="INT" val="3" />
			<add order="0x40" stat="CON" val="4" />
			<add order="0x40" stat="DEX" val="4" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24913" name="o_july_shirt_stat_15">
		<!-- INT +4. STR +4. CON +4. MEN +4. -->
		<for>
			<add order="0x40" stat="STR" val="4" />
			<add order="0x40" stat="INT" val="4" />
			<add order="0x40" stat="CON" val="4" />
			<add order="0x40" stat="DEX" val="4" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24914" name="o_july_shirt_stat_16">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24915" name="o_july_shirt_stat_17">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24916" name="o_july_shirt_stat_18">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24917" name="o_july_shirt_stat_19">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24918" name="o_july_shirt_stat_20">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24919" name="o_july_shirt_stat_21">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24920" name="o_july_shirt_stat_22">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24921" name="o_july_shirt_stat_23">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24922" name="o_july_shirt_stat_24">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24923" name="o_july_shirt_stat_25">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24924" name="o_july_shirt_stat_26">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
			<add order="0x40" stat="CON" val="5" />
			<add order="0x40" stat="DEX" val="5" />
			<add order="0x40" stat="WIT" val="0" />
			<add order="0x40" stat="MEN" val="0" />
		</for>
	</option>
	<option id="24925" name="o_july_shirt_stat_27">
		<!-- INT +5. STR +5. CON +5. MEN +5. -->
		<for>
			<add order="0x40" stat="STR" val="5" />
			<add order="0x40" stat="INT" val="5" />
