=== mikesaidani/L2JDatapack/L2J_DataPack_BETA/dist/game/data/xsd/skills.xsd
<?xml version="1.1" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:complexType name="tableType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="setType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" use="optional" />
				<xs:attribute type="xs:string" name="val" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="enchantType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="name" use="optional" />
				<xs:attribute type="xs:string" name="val" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="usingType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="kind" use="optional" />
				<xs:attribute type="xs:string" name="slot" use="optional" />
				<xs:attribute type="xs:string" name="weaponChange" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="playerType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="Charges" use="optional" />
				<xs:attribute type="xs:string" name="canSummon" use="optional" />
				<xs:attribute type="xs:string" name="canResurrect" use="optional" />
				<xs:attribute type="xs:string" name="canSweep" use="optional" />
				<xs:attribute type="xs:string" name="canSummonSiegeGolem" use="optional" />
				<xs:attribute type="xs:byte" name="invSize" use="optional" />
				<xs:attribute type="xs:byte" name="weight" use="optional" />
				<xs:attribute type="xs:byte" name="hp" use="optional" />
				<xs:attribute type="xs:byte" name="cp" use="optional" />
				<xs:attribute type="xs:byte" name="mp" use="optional" />
				<xs:attribute type="xs:byte" name="souls" use="optional" />
				<xs:attribute type="xs:string" name="canTransform" use="optional" />
				<xs:attribute type="xs:string" name="canUntransform" use="optional" />
				<xs:attribute type="xs:byte" name="transformationId" use="optional" />
				<xs:attribute type="xs:string" name="canCreateBase" use="optional" />
				<xs:attribute type="xs:string" name="canCreateOutpost" use="optional" />
				<xs:attribute type="xs:string" name="canTakeCastle" use="optional" />
				<xs:attribute type="xs:string" name="canTakeFort" use="optional" />
				<xs:attribute type="xs:byte" name="canRefuelAirship" use="optional" />
				<xs:attribute type="xs:string" name="canEscape" use="optional" />
				<xs:attribute type="xs:string" name="active_effect_id_lvl" use="optional" />
				<xs:attribute type="xs:string" name="active_skill_id" use="optional" />
				<xs:attribute type="xs:string" name="active_skill_id_lvl" use="optional" />
				<xs:attribute type="xs:string" name="checkAbnormal" use="optional" />
				<xs:attribute type="xs:byte" name="SiegeZone" use="optional" />
				<xs:attribute type="xs:string" name="callPc" use="optional" />
				<xs:attribute type="xs:byte" name="clanHall" use="optional" />
				<xs:attribute type="xs:byte" name="sex" use="optional" />
				<xs:attribute type="xs:string" name="npcIdRadius" use="optional" />
				<xs:attribute type="xs:string" name="landingZone" use="optional" />
				<xs:attribute type="xs:string" name="insideZoneId" use="optional" />
				<xs:attribute type="xs:string" name="chaotic" use="optional" />
				<xs:attribute type="xs:string" name="resting" use="optional" />
				<xs:attribute type="xs:string" name="standing" use="optional" />
				<xs:attribute type="xs:string" name="moving" use="optional" />
				<xs:attribute type="xs:string" name="running" use="optional" />
				<xs:attribute type="xs:string" name="flying" use="optional" />
				<xs:attribute type="xs:string" name="front" use="optional" />
				<xs:attribute type="xs:string" name="behind" use="optional" />
				<xs:attribute type="xs:string" name="levelRange" use="optional" />
				<xs:attribute type="xs:byte" name="instanceId" use="optional" />
				<xs:attribute type="xs:string" name="flyMounted" use="optional" />
				<xs:attribute type="xs:string" name="active_effect_id" use="optional" />
				<xs:attribute type="xs:string" name="agathionId" use="optional" />
				<xs:attribute type="xs:byte" name="fort" use="optional" />
				<xs:attribute type="xs:byte" name="level" use="optional" />
				<xs:attribute type="xs:string" name="class_id_restriction" use="optional" />
				<xs:attribute type="xs:short" name="siegeZone" use="optional" />
				<xs:attribute type="xs:byte" name="siegeSide" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="targetType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:short" name="mindistance" use="optional" />
				<xs:attribute type="xs:byte" name="abnormal" use="optional" />
				<xs:attribute type="xs:short" name="active_effect_id" use="optional" />
				<xs:attribute type="xs:short" name="active_skill_id" use="optional" />
				<xs:attribute type="xs:string" name="class_id_restriction" use="optional" />
				<xs:attribute type="xs:string" name="myPartyExceptMe" use="optional" />
				<xs:attribute type="xs:string" name="race" use="optional" />
				<xs:attribute type="xs:string" name="npcId" use="optional" />
				<xs:attribute type="xs:string" name="npcType" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="notType">
		<xs:sequence>
			<xs:element name="using" minOccurs="0" type="usingType" />
			<xs:element name="player" minOccurs="0" type="playerType" />
			<xs:element name="target" minOccurs="0" type="targetType" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="gameType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="night" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="andType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="using" type="usingType" />
			<xs:element name="player" type="playerType" />
			<xs:element name="target" type="targetType" />
			<xs:element name="not" type="notType" />
			<xs:element name="game" type="gameType" />
			<xs:element name="or" minOccurs="0" type="andType" />
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="condType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="using" type="usingType" />
			<xs:element name="and" type="andType" />
			<xs:element name="not" type="notType" />
			<xs:element name="player" type="playerType" />
			<xs:element name="target" type="targetType" />
		</xs:choice>
		<xs:attribute type="xs:short" name="msgId" use="optional" />
		<xs:attribute type="xs:byte" name="addName" use="optional" />
		<xs:attribute type="xs:string" name="msg" use="optional" />
	</xs:complexType>
	<xs:complexType name="paramType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="chance" use="optional" />
				<xs:attribute type="xs:string" name="power" use="optional" />
				<xs:attribute type="xs:byte" name="criticalChance" use="optional" />
				<xs:attribute type="xs:string" name="charge" use="optional" />
				<xs:attribute type="xs:byte" name="cubicId" use="optional" />
				<xs:attribute type="xs:byte" name="cubicDelay" use="optional" />
				<xs:attribute type="xs:short" name="cubicDuration" use="optional" />
				<xs:attribute type="xs:short" name="cubicMaxCount" use="optional" />
				<xs:attribute type="xs:byte" name="cubicSkillChance" use="optional" />
				<xs:attribute type="xs:string" name="cubicPower" use="optional" />
				<xs:attribute type="xs:string" name="npcId" use="optional" />
				<xs:attribute type="xs:string" name="consumeItemId" use="optional" />
				<xs:attribute type="xs:string" name="consumeItemCount" use="optional" />
				<xs:attribute type="xs:string" name="lifeTime" use="optional" />
				<xs:attribute type="xs:string" name="dispel" use="optional" />
				<xs:attribute type="xs:string" name="expMultiplier" use="optional" />
				<xs:attribute type="xs:string" name="halfLethal" use="optional" />
				<xs:attribute type="xs:byte" name="cubicSkill1Chance" use="optional" />
				<xs:attribute type="xs:byte" name="cubicSkill2Chance" use="optional" />
				<xs:attribute type="xs:byte" name="cubicSkill3Chance" use="optional" />
				<xs:attribute type="xs:string" name="BUG_WEAKNESS" use="optional" />
				<xs:attribute type="xs:string" name="BEAST_WEAKNESS" use="optional" />
				<xs:attribute type="xs:string" name="ANIMAL_WEAKNESS" use="optional" />
				<xs:attribute type="xs:string" name="DRAGON_WEAKNESS" use="optional" />
				<xs:attribute type="xs:string" name="PLANT_WEAKNESS" use="optional" />
				<xs:attribute type="xs:string" name="ROOT_PHYSICALLY" use="optional" />
				<xs:attribute type="xs:string" name="HOLD" use="optional" />
				<xs:attribute type="xs:string" name="BOW" use="optional" />
				<xs:attribute type="xs:string" name="CROSSBOW" use="optional" />
				<xs:attribute type="xs:string" name="SLEEP" use="optional" />
				<xs:attribute type="xs:string" name="POISON" use="optional" />
				<xs:attribute type="xs:string" name="cubicCount" use="optional" />
				<xs:attribute type="xs:string" name="SHOCK" use="optional" />
				<xs:attribute type="xs:string" name="ignoreShieldDefence" use="optional" />
				<xs:attribute type="xs:string" name="POLE" use="optional" />
				<xs:attribute type="xs:string" name="PARALYZE" use="optional" />
				<xs:attribute type="xs:string" name="isAdvanced" use="optional" />
				<xs:attribute type="xs:string" name="DERANGEMENT" use="optional" />
				<xs:attribute type="xs:string" name="BLEED" use="optional" />
				<xs:attribute type="xs:string" name="slot" use="optional" />
				<xs:attribute type="xs:string" name="rate" use="optional" />
				<xs:attribute type="xs:string" name="max" use="optional" />
				<xs:attribute type="xs:string" name="CONSTRUCT_WEAKNESS" use="optional" />
				<xs:attribute type="xs:string" name="GIANT_WEAKNESS" use="optional" />
				<xs:attribute type="xs:string" name="SWORD" use="optional" />
				<xs:attribute type="xs:string" name="BLUNT" use="optional" />
				<xs:attribute type="xs:string" name="DAGGER" use="optional" />
				<xs:attribute type="xs:string" name="DUAL" use="optional" />
				<xs:attribute type="xs:string" name="DUALFIST" use="optional" />
				<xs:attribute type="xs:string" name="ANCIENTSWORD" use="optional" />
				<xs:attribute type="xs:string" name="RAPIER" use="optional" />
				<xs:attribute type="xs:string" name="DUALDAGGER" use="optional" />
				<xs:attribute type="xs:string" name="fullLethal" use="optional" />
				<xs:attribute type="xs:string" name="attackerType" use="optional" />
				<xs:attribute type="xs:byte" name="minAttackerLevel" use="optional" />
				<xs:attribute type="xs:byte" name="maxAttackerLevel" use="optional" />
				<xs:attribute type="xs:boolean" name="isCritical" use="optional" />
				<xs:attribute type="xs:string" name="minDamage" use="optional" />
				<xs:attribute type="xs:short" name="castSkillId" use="optional" />
				<xs:attribute type="xs:byte" name="blockedActions" use="optional" />
				<xs:attribute type="xs:string" name="skillId" use="optional" />
				<xs:attribute type="xs:string" name="skillLevel" use="optional" />
				<xs:attribute type="xs:string" name="allowWeapons" use="optional" />
				<xs:attribute type="xs:string" name="targetType" use="optional" />
				<xs:attribute type="xs:byte" name="npcCount" use="optional" />
				<xs:attribute type="xs:string" name="expNeeded" use="optional" />
				<xs:attribute type="xs:string" name="itemId" use="optional" />
				<xs:attribute type="xs:string" name="itemCount" use="optional" />
				<xs:attribute type="xs:short" name="id" use="optional" />
				<xs:attribute type="xs:short" name="amount" use="optional" />
				<xs:attribute type="xs:int" name="despawnDelay" use="optional" />
				<xs:attribute type="xs:string" name="isSummonSpawn" use="optional" />
				<xs:attribute type="xs:string" name="escapeType" use="optional" />
				<xs:attribute type="xs:string" name="slots" use="optional" />
				<xs:attribute type="xs:string" name="value" use="optional" />
				<xs:attribute type="xs:string" name="sp" use="optional" />
				<xs:attribute type="xs:string" name="x" use="optional" />
				<xs:attribute type="xs:string" name="y" use="optional" />
				<xs:attribute type="xs:string" name="z" use="optional" />
				<xs:attribute type="xs:string" name="grade" use="optional" />
				<xs:attribute type="xs:byte" name="VALAKAS" use="optional" />
				<xs:attribute type="xs:string" name="isItem" use="optional" />
				<xs:attribute type="xs:byte" name="skillLvl" use="optional" />
				<xs:attribute type="xs:byte" name="GUST" use="optional" />
				<xs:attribute type="xs:byte" name="BOSS" use="optional" />
				<xs:attribute type="xs:byte" name="PHYSICAL_BLOCKADE" use="optional" />
				<xs:attribute type="xs:string" name="canKill" use="optional" />
				<xs:attribute type="xs:string" name="TURN_STONE" use="optional" />
				<xs:attribute type="xs:byte" name="FIST" use="optional" />
				<xs:attribute type="xs:byte" name="randomOffset" use="optional" />
				<xs:attribute type="xs:short" name="skillId1" use="optional" />
				<xs:attribute type="xs:short" name="skillId2" use="optional" />
				<xs:attribute type="xs:short" name="skillId3" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="addType" mixed="true">
		<xs:all>
			<xs:element name="using" minOccurs="0" type="usingType" />
			<xs:element name="and" minOccurs="0" type="andType" />
			<xs:element name="not" minOccurs="0" type="notType" />
			<xs:element name="player" minOccurs="0" type="playerType" />
			<xs:element name="game" minOccurs="0" type="gameType" />
		</xs:all>
		<xs:attribute type="xs:string" name="order" use="optional" />
		<xs:attribute type="xs:string" name="stat" use="optional" />
		<xs:attribute type="xs:string" name="val" use="optional" />
	</xs:complexType>
	<xs:complexType name="shareType">
		<xs:simpleContent>
			<xs:extension base="xs:string">
				<xs:attribute type="xs:string" name="order" use="optional" />
				<xs:attribute type="xs:string" name="stat" use="optional" />
				<xs:attribute type="xs:float" name="val" use="optional" />
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="effectType" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="param" type="paramType" />
			<xs:element name="add" type="addType" />
			<xs:element name="mul" type="addType" />
			<xs:element name="sub" type="addType" />
			<xs:element name="basemul" type="addType" />
			<xs:element name="set" type="addType" />
			<xs:element name="share" type="shareType" />
		</xs:choice>
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:string" name="ticks" use="optional" />
		<xs:attribute type="xs:string" name="abnormalTime" use="optional" />
		<xs:attribute type="xs:string" name="activationChance" use="optional" />
		<xs:attribute type="xs:string" name="chanceType" use="optional" />
		<xs:attribute type="xs:string" name="triggeredId" use="optional" />
		<xs:attribute type="xs:string" name="triggeredLevel" use="optional" />
		<xs:attribute type="xs:string" name="activationMinDamage" use="optional" />
		<xs:attribute type="xs:short" name="activationSkills" use="optional" />
	</xs:complexType>
	<xs:complexType name="forType" mixed="true">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="effect" type="effectType" />
			<xs:element name="param" type="paramType" />
			<xs:element name="add" type="addType" />
			<xs:element name="mul" type="addType" />
			<xs:element name="sub" type="addType" />
			<xs:element name="basemul" type="addType" />
			<xs:element name="set" type="addType" />
		</xs:choice>
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:byte" name="val" use="optional" />
	</xs:complexType>
	<xs:complexType name="effectsType">
		<xs:sequence>
			<xs:element name="effect" type="effectType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="skillType">
		<xs:choice maxOccurs="unbounded" minOccurs="0">
			<xs:element name="table" type="tableType" />
			<xs:element name="set" type="setType" />
			<xs:element name="enchant1" type="enchantType" />
			<xs:element name="enchant2" type="enchantType" />
			<xs:element name="enchant3" type="enchantType" />
			<xs:element name="enchant4" type="enchantType" />
			<xs:element name="enchant5" type="enchantType" />
			<xs:element name="enchant6" type="enchantType" />
			<xs:element name="enchant7" type="enchantType" />
			<xs:element name="enchant8" type="enchantType" />
			<xs:element name="cond" type="condType" />
			<xs:element name="for" type="forType" />
			<xs:element name="enchant1for" type="forType" />
			<xs:element name="enchant2for" type="forType" />
			<xs:element name="enchant2pvpEffects" type="effectsType" />
			<xs:element name="enchant2pveEffects" type="effectsType" />
			<xs:element name="enchant7for" type="forType" />
			<xs:element name="enchant7pvpEffects" type="effectsType" />
			<xs:element name="enchant7pveEffects" type="effectsType" />
			<xs:element name="enchant3for" type="forType" />
			<xs:element name="enchant4for" type="forType" />
			<xs:element name="enchant5for" type="forType" />
			<xs:element name="enchant6for" type="forType" />
			<xs:element name="endEffects" type="effectsType" />
			<xs:element name="selfEffects" type="effectsType" />
			<xs:element name="enchant2selfEffects" type="effectsType" />
			<xs:element name="effect" type="effectType" />
			<xs:element name="enchant1cond" type="condType" />
			<xs:element name="enchant4selfEffects" type="effectsType" />
			<xs:element name="pvpEffects" type="effectsType" />
			<xs:element name="pveEffects" type="effectsType" />
			<xs:element name="channelingEffects" type="effectsType" />
			<xs:element name="startEffects" type="effectsType" />
		</xs:choice>
		<xs:attribute type="xs:short" name="id" use="optional" />
		<xs:attribute type="xs:byte" name="levels" use="optional" />
		<xs:attribute type="xs:string" name="name" use="optional" />
		<xs:attribute type="xs:byte" name="enchantGroup1" use="optional" />
		<xs:attribute type="xs:byte" name="enchantGroup2" use="optional" />
		<xs:attribute type="xs:byte" name="enchantGroup3" use="optional" />
		<xs:attribute type="xs:byte" name="enchantGroup4" use="optional" />
		<xs:attribute type="xs:byte" name="enchantGroup5" use="optional" />
		<xs:attribute type="xs:byte" name="enchantGroup6" use="optional" />
		<xs:attribute type="xs:byte" name="enchantGroup7" use="optional" />
		<xs:attribute type="xs:byte" name="enchantGroup8" use="optional" />
	</xs:complexType>

	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="skill" type="skillType" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mikesaidani/L2JDatapack/L2J_DataPack_BETA/dist/game/data/stats/skills/21000-21099.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/skills.xsd">
	<skill id="21000" levels="1" name="Release Seal on Agathion - Majo">
		<!-- Confirmed CT2.5 -->
		<set name="hitTime" val="3000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="85" />
		<set name="npcId" val="1501" />
		<set name="operateType" val="A1" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="SummonAgathion" noicon="1" val="0" />
		</for>
	</skill>
	<skill id="21001" levels="1" name="Release Seal on Agathion - Gold Majo">
		<!-- Confirmed CT2.5 -->
		<set name="hitTime" val="3000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="85" />
		<set name="npcId" val="1502" />
		<set name="operateType" val="A1" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="SummonAgathion" noicon="1" val="0" />
		</for>
	</skill>
	<skill id="21002" levels="1" name="Release Seal on Agathion - Black Majo">
		<!-- Confirmed CT2.5 -->
		<set name="hitTime" val="3000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="85" />
		<set name="npcId" val="1503" />
		<set name="operateType" val="A1" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="SummonAgathion" noicon="1" val="0" />
		</for>
	</skill>
	<skill id="21003" levels="1" name="Release Seal on Agathion - Plaipitak">
		<!-- Confirmed CT2.5 -->
		<set name="hitTime" val="3000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="85" />
		<set name="npcId" val="1504" />
		<set name="operateType" val="A1" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="SummonAgathion" noicon="1" val="0" />
		</for>
	</skill>
	<skill id="21004" levels="1" name="Wind Walk">
		<set name="abnormalLvl" val="26" />
		<set name="abnormalTime" val="120" />
		<set name="abnormalType" val="SPEED_UP" />
		<set name="hitTime" val="4000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="operateType" val="A2" />
		<set name="reuseDelay" val="1080000" />
		<set name="skillType" val="BUFF" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="Buff" val="0">
				<add order="0x40" stat="runSpd" val="20" />
			</effect>
		</for>
	</skill>
	<skill id="21005" levels="1" name="Agility">
		<set name="abnormalLvl" val="26" />
		<set name="abnormalTime" val="3600" />
		<set name="abnormalType" val="AVOID_UP" />
		<set name="hitTime" val="4000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="operateType" val="A2" />
		<set name="reuseDelay" val="86400000" />
		<set name="skillType" val="BUFF" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="Buff" val="0">
				<add order="0x40" stat="rEvas" val="4" />
			</effect>
		</for>
	</skill>
	<skill id="21006" levels="1" name="Large Firework Effect">
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="1" />
		<set name="operateType" val="A1" />
		<set name="reuseDelay" val="3600000" />
		<set name="skillType" val="NOTDONE" />
		<set name="targetType" val="NONE" />
	</skill>
	<skill id="21007" levels="1" name="Ability of Doubt">
		<!-- Confirmed CT2.5 -->
		<set name="abnormalTime" val="600" />
		<set name="abnormalLvl" val="0" />
		<set name="abnormalType" val="BIG_HEAD" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="operateType" val="A2" />
		<set name="reuseDelay" val="3600000" />
		<set name="skillType" val="BUFF" />
		<set name="targetType" val="SELF" />
		<set name="trait" val="ETC" />
		<for>
			<effect name="BigHead" val="0" abnormalVisualEffect="bighead" />
		</for>
	</skill>
	<skill id="21008" levels="1" name="Release Seal on Agathion - Baby Panda">
		<!-- Confirmed CT2.5 -->
		<set name="hitTime" val="3000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="85" />
		<set name="npcId" val="1505" />
		<set name="operateType" val="A1" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="SummonAgathion" noicon="1" val="0" />
		</for>
	</skill>
	<skill id="21009" levels="1" name="Release Seal on Agathion - Bamboo Panda">
		<!-- Confirmed CT2.5 -->
		<set name="hitTime" val="3000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="85" />
		<set name="npcId" val="1506" />
		<set name="operateType" val="A1" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="SummonAgathion" noicon="1" val="0" />
		</for>
	</skill>
	<skill id="21010" levels="1" name="Release Seal on Agathion - Sexy Panda">
		<!-- Confirmed CT2.5 -->
		<set name="hitTime" val="3000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="85" />
		<set name="npcId" val="1507" />
		<set name="operateType" val="A1" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="SummonAgathion" noicon="1" val="0" />
		</for>
	</skill>
	<skill id="21011" levels="1" name="Energy Recovery">
		<!-- Recovers energy when acquiring Exp. for 20 minutes -->
		<set name="abnormalLvl" val="26" />
		<set name="abnormalTime" val="1200" />
		<set name="abnormalType" val="VP_UP" />
		<set name="hitTime" val="4000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="operateType" val="A2" />
		<set name="reuseDelay" val="43200000" />
		<set name="skillType" val="BUFF" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="Buff" val="0" abnormalVisualEffect="vitality">
				<sub order="0x40" stat="vitalityConsumeRate" val="10" />
			</effect>
		</for>
	</skill>
	<skill id="21012" levels="1" name="Energy Recovery">
		<!-- Recovers energy when acquiring Exp. for 20 minutes -->
		<set name="abnormalLvl" val="26" />
		<set name="abnormalTime" val="1200" />
		<set name="abnormalType" val="VP_UP" />
		<set name="hitTime" val="4000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="operateType" val="A2" />
		<set name="reuseDelay" val="43200000" />
		<set name="skillType" val="BUFF" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="Buff" val="0" abnormalVisualEffect="vitality">
				<sub order="0x40" stat="vitalityConsumeRate" val="10" />
			</effect>
		</for>
	</skill>
	<skill id="21013" levels="1" name="Energy Recovery">
		<!-- Recovers energy when acquiring Exp. for 20 minutes -->
		<set name="abnormalLvl" val="26" />
		<set name="abnormalTime" val="1200" />
		<set name="abnormalType" val="VP_UP" />
		<set name="hitTime" val="4000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="operateType" val="A2" />
		<set name="reuseDelay" val="43200000" />
		<set name="skillType" val="BUFF" />
		<set name="targetType" val="SELF" />
		<for>
			<effect name="Buff" val="0" abnormalVisualEffect="vitality">
				<sub order="0x40" stat="vitalityConsumeRate" val="10" />
			</effect>
		</for>
	</skill>
	<skill id="21014" levels="1" name="Scissors">
		<set name="castRange" val="400" />
		<set name="coolTime" val="500" />
		<set name="effectRange" val="500" />
		<set name="hitTime" val="2000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="1" />
		<set name="operateType" val="A1" />
		<set name="targetType" val="ONE" />
		<cond msgId="109">
			<target npcId="13183" />
		</cond>
	</skill>
	<skill id="21015" levels="1" name="Rock">
		<set name="castRange" val="400" />
		<set name="coolTime" val="500" />
		<set name="hitTime" val="2000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="1" />
		<set name="operateType" val="A1" />
		<set name="targetType" val="ONE" />
		<cond msgId="109">
			<target npcId="13183" />
		</cond>
	</skill>
	<skill id="21016" levels="1" name="Paper">
		<set name="castRange" val="400" />
		<set name="coolTime" val="500" />
		<set name="hitTime" val="2000" />
		<set name="isMagic" val="2" /> <!-- Static Skill -->
		<set name="magicLvl" val="1" />
		<set name="operateType" val="A1" />
		<set name="targetType" val="ONE" />
		<cond msgId="109">
			<target npcId="13183" />
		</cond>
	</skill>
	<skill id="21017" levels="1" name="Holiday Dream Weapon">
		<set name="magicLvl" val="1" />
		<set name="operateType" val="P" />
		<set name="targetType" val="SELF" />
		<for>
			<mul order="0x30" stat="maxCp" val="1.3" />
			<add order="0x40" stat="rCrit" val="100" />
			<add order="0x40" stat="absorbDam" val="10" />
		</for>
	</skill>
	<skill id="21018" levels="1" name="Holiday Dream Weapon">
		<set name="magicLvl" val="1" />
		<set name="operateType" val="P" />
		<set name="targetType" val="SELF" />
		<for>
			<mul order="0x30" stat="maxCp" val="1.3" />
			<add order="0x40" stat="rCrit" val="100" />
			<mul order="0x30" stat="cAtk" val="1.25" />
		</for>
	</skill>
	<skill id="21019" levels="1" name="Holiday Dream Weapon">
		<set name="magicLvl" val="1" />
		<set name="operateType" val="P" />
		<set name="targetType" val="SELF" />
		<for>
			<mul order="0x30" stat="maxCp" val="1.3" />
			<mul order="0x30" stat="blowRate" val="1.25" />
			<mul order="0x30" stat="MagicalMpConsumeRate" val="0.8" />
		</for>
	</skill>
	<skill id="21020" levels="1" name="Holiday Dream Weapon">
		<set name="magicLvl" val="1" />
		<set name="operateType" val="P" />
		<set name="targetType" val="SELF" />
		<for>
			<mul order="0x30" stat="maxCp" val="1.3" />
			<add order="0x40" stat="rCrit" val="100" />
			<add order="0x40" stat="absorbDam" val="10" />
		</for>
	</skill>
	<skill id="21021" levels="1" name="Holiday Dream Weapon">
		<set name="magicLvl" val="1" />
		<set name="operateType" val="P" />
