=== mikesaidani/L2JDatapack/L2J_DataPack_BETA/dist/game/data/xsd/transformations.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="transform">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Male">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="collision" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:float" name="radius" />
														<xs:attribute type="xs:float" name="height" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="moving" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:float" name="walk" />
														<xs:attribute type="xs:float" name="run" />
														<xs:attribute type="xs:float" name="waterWalk" />
														<xs:attribute type="xs:float" name="waterRun" />
														<xs:attribute type="xs:float" name="flyWalk" />
														<xs:attribute type="xs:float" name="flyRun" />
														<xs:attribute type="xs:float" name="unknownWalk" />
														<xs:attribute type="xs:float" name="unknownRun" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="skills" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="skill" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:short" name="id" use="optional" />
																	<xs:attribute type="xs:byte" name="level" use="optional" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="additional_skills" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="skill" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:short" name="id" use="optional" />
																	<xs:attribute type="xs:byte" name="level" use="optional" />
																	<xs:attribute type="xs:byte" name="minLevel" use="optional" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="actions" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string" name="base_attack_type" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="base_attack_range" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:byte" name="base_random_damage" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:short" name="base_attack_speed" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:byte" name="base_critical_prob" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:byte" name="base_physical_attack" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:byte" name="base_magical_attack" minOccurs="0" maxOccurs="1" />
										<xs:element name="items" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:integer" name="id" />
																	<xs:attribute type="xs:boolean" name="allowed" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="basic_stat" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:byte" name="str" />
														<xs:attribute type="xs:byte" name="int" />
														<xs:attribute type="xs:byte" name="con" />
														<xs:attribute type="xs:byte" name="dex" />
														<xs:attribute type="xs:byte" name="wit" />
														<xs:attribute type="xs:byte" name="men" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="base_defend" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:byte" name="chest" />
														<xs:attribute type="xs:byte" name="legs" />
														<xs:attribute type="xs:byte" name="head" />
														<xs:attribute type="xs:byte" name="feet" />
														<xs:attribute type="xs:byte" name="gloves" />
														<xs:attribute type="xs:byte" name="underwear" />
														<xs:attribute type="xs:byte" name="cloak" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="base_magic_defend" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:byte" name="rear" />
														<xs:attribute type="xs:byte" name="lear" />
														<xs:attribute type="xs:byte" name="rfinger" />
														<xs:attribute type="xs:byte" name="lfinger" />
														<xs:attribute type="xs:byte" name="neck" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="levels" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="level" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:byte" name="val" use="optional" />
																	<xs:attribute type="xs:float" name="bonus" use="optional" />
																	<xs:attribute type="xs:float" name="hp_regen" use="optional" />
																	<xs:attribute type="xs:float" name="mp_regen" use="optional" />
																	<xs:attribute type="xs:float" name="cp_regen" use="optional" />
																	<xs:attribute type="xs:short" name="str" use="optional" />
																	<xs:attribute type="xs:short" name="int" use="optional" />
																	<xs:attribute type="xs:short" name="con" use="optional" />
																	<xs:attribute type="xs:byte" name="dex" use="optional" />
																	<xs:attribute type="xs:short" name="wit" use="optional" />
																	<xs:attribute type="xs:short" name="men" use="optional" />
																	<xs:attribute type="xs:float" name="hp" use="optional" />
																	<xs:attribute type="xs:float" name="mp" use="optional" />
																	<xs:attribute type="xs:float" name="cp" use="optional" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="Female">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="collision" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:float" name="radius" />
														<xs:attribute type="xs:float" name="height" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="moving" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:float" name="walk" />
														<xs:attribute type="xs:float" name="run" />
														<xs:attribute type="xs:float" name="waterWalk" />
														<xs:attribute type="xs:float" name="waterRun" />
														<xs:attribute type="xs:float" name="flyWalk" />
														<xs:attribute type="xs:float" name="flyRun" />
														<xs:attribute type="xs:float" name="unknownWalk" />
														<xs:attribute type="xs:float" name="unknownRun" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="skills" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="skill" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:short" name="id" use="optional" />
																	<xs:attribute type="xs:byte" name="level" use="optional" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="additional_skills" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="skill" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:short" name="id" use="optional" />
																	<xs:attribute type="xs:byte" name="level" use="optional" />
																	<xs:attribute type="xs:byte" name="minLevel" use="optional" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="actions" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:string" name="base_attack_type" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:integer" name="base_attack_range" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:byte" name="base_random_damage" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:short" name="base_attack_speed" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:byte" name="base_critical_prob" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:byte" name="base_physical_attack" minOccurs="0" maxOccurs="1" />
										<xs:element type="xs:byte" name="base_magical_attack" minOccurs="0" maxOccurs="1" />
										<xs:element name="items" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="item" maxOccurs="unbounded">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:integer" name="id" />
																	<xs:attribute type="xs:boolean" name="allowed" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="basic_stat" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:byte" name="str" />
														<xs:attribute type="xs:byte" name="int" />
														<xs:attribute type="xs:byte" name="con" />
														<xs:attribute type="xs:byte" name="dex" />
														<xs:attribute type="xs:byte" name="wit" />
														<xs:attribute type="xs:byte" name="men" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="base_defend" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:byte" name="chest" />
														<xs:attribute type="xs:byte" name="legs" />
														<xs:attribute type="xs:byte" name="head" />
														<xs:attribute type="xs:byte" name="feet" />
														<xs:attribute type="xs:byte" name="gloves" />
														<xs:attribute type="xs:byte" name="underwear" />
														<xs:attribute type="xs:byte" name="cloak" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="base_magic_defend" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:simpleContent>
													<xs:extension base="xs:string">
														<xs:attribute type="xs:byte" name="rear" />
														<xs:attribute type="xs:byte" name="lear" />
														<xs:attribute type="xs:byte" name="rfinger" />
														<xs:attribute type="xs:byte" name="lfinger" />
														<xs:attribute type="xs:byte" name="neck" />
													</xs:extension>
												</xs:simpleContent>
											</xs:complexType>
										</xs:element>
										<xs:element name="levels" minOccurs="0" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="level" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute type="xs:byte" name="val" use="optional" />
																	<xs:attribute type="xs:float" name="bonus" use="optional" />
																	<xs:attribute type="xs:float" name="hp_regen" use="optional" />
																	<xs:attribute type="xs:float" name="mp_regen" use="optional" />
																	<xs:attribute type="xs:float" name="cp_regen" use="optional" />
																	<xs:attribute type="xs:short" name="str" use="optional" />
																	<xs:attribute type="xs:short" name="int" use="optional" />
																	<xs:attribute type="xs:short" name="con" use="optional" />
																	<xs:attribute type="xs:byte" name="dex" use="optional" />
																	<xs:attribute type="xs:short" name="wit" use="optional" />
																	<xs:attribute type="xs:short" name="men" use="optional" />
																	<xs:attribute type="xs:float" name="hp" use="optional" />
																	<xs:attribute type="xs:float" name="mp" use="optional" />
																	<xs:attribute type="xs:float" name="cp" use="optional" />
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute type="xs:short" name="id" />
						<xs:attribute type="xs:string" name="type" />
						<xs:attribute type="xs:byte" name="can_swim" />
						<xs:attribute type="xs:short" name="spawn_height" use="optional" />
						<xs:attribute type="xs:byte" name="normal_attackable" />
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== mikesaidani/L2JDatapack/L2J_DataPack_BETA/dist/game/data/stats/transformations/00253.xml
<?xml version="1.0" encoding="UTF-8"?>
<list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../xsd/transformations.xsd">
	<transform id="253" type="COMBAT" can_swim="0" normal_attackable="1">
		<Male>
			<collision radius="14.5" height="29" />
			<moving walk="30" run="125" waterWalk="50" waterRun="50" flyWalk="0" flyRun="0" unknownWalk="0" unknownRun="0" />
			<skills>
				<skill id="675" level="1" /> <!-- Divine Warrior Cross Slash -->
				<skill id="676" level="1" /> <!-- Divine Warrior Sonic Blaster -->
				<skill id="677" level="1" /> <!-- Divine Warrior Transfixion of Earth -->
				<skill id="678" level="1" /> <!-- Divine Warrior War Cry -->
				<skill id="679" level="1" /> <!-- Sacrifice Warrior -->
				<skill id="798" level="1" /> <!-- Divine Warrior Assault Attack -->
				<skill id="619" level="1" /> <!-- Transform Dispel -->
				<skill id="5491" level="1" /> <!-- Decrease Bow/Crossbow Atk. Spd. -->
			</skills>
			<actions>1 2 3 4 5 6 7 8 9 11 15 16 17 18 19 21 22 23 32 36 39 40 41 42 43 44 45 46 47 48 50 52 53 54 55 56 57 63 64 65 70 1000 1001 1003 1004 1005 1006 1007 1008 1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1022 1023 1024 1025 1026 1027 1028 1029 1030 1031 1032 1033 1034 1035 1036 1037 1038 1039 1040 1041 1042 1043 1044 1045 1046 1047 1048 1049 1050 1051 1052 1053 1054 1055 1056 1057 1058 1059 1060 1061 1062 1063 1064 1065 1066 1067 1068 1069 1070 1071 1072 1073 1074 1075 1076 1077 1078 1079 1080 1081 1082 1083 1084 1089 1090 1091 1092 1093 1094 1095 1096 1097 1098</actions>
			<base_attack_type>sword</base_attack_type>
			<base_attack_range>20</base_attack_range>
			<base_random_damage>10</base_random_damage>
			<base_attack_speed>300</base_attack_speed>
			<base_critical_prob>5</base_critical_prob>
			<base_physical_attack>5</base_physical_attack>
			<base_magical_attack>5</base_magical_attack>
			<basic_stat str="40" int="21" con="43" dex="30" wit="11" men="25" />
			<base_defend chest="31" legs="18" head="12" feet="7" gloves="8" underwear="3" cloak="1" />
			<base_magic_defend rear="9" lear="9" rfinger="5" lfinger="5" neck="13" />
			<levels>
				<level val="1" bonus="0.9" hp_regen="2.0" mp_regen="0.9" cp_regen="2.0" str="-70" int="-45" con="-54" dex="-15" wit="-60" men="1" hp="88.0" mp="33.0" cp="44.0" />
				<level val="2" bonus="0.91" hp_regen="2.05" mp_regen="0.9" cp_regen="2.0" str="-69" int="-44" con="-53" dex="-14" wit="-58" men="2" hp="101.013" mp="39.006" cp="50.5065" />
				<level val="3" bonus="0.92" hp_regen="2.1" mp_regen="0.9" cp_regen="2.0" str="-68" int="-43" con="-52" dex="-14" wit="-56" men="3" hp="114.169" mp="45.078" cp="57.0845" />
				<level val="4" bonus="0.93" hp_regen="2.15" mp_regen="0.9" cp_regen="2.0" str="-66" int="-42" con="-50" dex="-13" wit="-54" men="4" hp="127.468" mp="51.216" cp="63.734" />
				<level val="5" bonus="0.94" hp_regen="2.2" mp_regen="0.9" cp_regen="2.0" str="-65" int="-41" con="-49" dex="-12" wit="-52" men="5" hp="140.91" mp="57.42" cp="70.455" />
				<level val="6" bonus="0.95" hp_regen="2.25" mp_regen="0.9" cp_regen="2.0" str="-64" int="-39" con="-47" dex="-11" wit="-49" men="6" hp="154.495" mp="63.69" cp="77.2475" />
				<level val="7" bonus="0.96" hp_regen="2.3" mp_regen="0.9" cp_regen="2.0" str="-63" int="-38" con="-46" dex="-10" wit="-47" men="7" hp="168.223" mp="70.026" cp="84.1115" />
				<level val="8" bonus="0.97" hp_regen="2.35" mp_regen="0.9" cp_regen="2.0" str="-61" int="-37" con="-44" dex="-10" wit="-44" men="8" hp="182.094" mp="76.428" cp="91.047" />
				<level val="9" bonus="0.98" hp_regen="2.4" mp_regen="0.9" cp_regen="2.0" str="-60" int="-36" con="-42" dex="-9" wit="-42" men="9" hp="196.108" mp="82.896" cp="98.054" />
				<level val="10" bonus="0.99" hp_regen="2.45" mp_regen="0.9" cp_regen="2.0" str="-58" int="-35" con="-41" dex="-8" wit="-39" men="11" hp="210.265" mp="89.43" cp="105.1325" />
				<level val="11" bonus="1.0" hp_regen="2.5" mp_regen="1.2" cp_regen="2.5" str="-57" int="-33" con="-39" dex="-7" wit="-36" men="12" hp="224.565" mp="96.03" cp="112.2825" />
				<level val="12" bonus="1.01" hp_regen="2.6" mp_regen="1.2" cp_regen="2.5" str="-55" int="-32" con="-37" dex="-6" wit="-32" men="13" hp="239.008" mp="102.696" cp="119.504" />
				<level val="13" bonus="1.02" hp_regen="2.7" mp_regen="1.2" cp_regen="2.5" str="-54" int="-31" con="-35" dex="-6" wit="-29" men="14" hp="253.594" mp="109.428" cp="126.797" />
				<level val="14" bonus="1.03" hp_regen="2.8" mp_regen="1.2" cp_regen="2.5" str="-52" int="-29" con="-33" dex="-5" wit="-25" men="15" hp="268.323" mp="116.226" cp="134.1615" />
				<level val="15" bonus="1.04" hp_regen="2.9" mp_regen="1.2" cp_regen="2.5" str="-50" int="-28" con="-31" dex="-4" wit="-22" men="16" hp="283.195" mp="123.09" cp="141.5975" />
				<level val="16" bonus="1.05" hp_regen="3.0" mp_regen="1.2" cp_regen="2.5" str="-49" int="-26" con="-29" dex="-3" wit="-18" men="17" hp="298.21" mp="130.02" cp="149.105" />
				<level val="17" bonus="1.06" hp_regen="3.1" mp_regen="1.2" cp_regen="2.5" str="-47" int="-25" con="-27" dex="-2" wit="-14" men="19" hp="313.368" mp="137.016" cp="156.684" />
				<level val="18" bonus="1.07" hp_regen="3.2" mp_regen="1.2" cp_regen="2.5" str="-45" int="-23" con="-25" dex="-1" wit="-9" men="20" hp="328.669" mp="144.078" cp="164.3345" />
				<level val="19" bonus="1.08" hp_regen="3.3" mp_regen="1.2" cp_regen="2.5" str="-43" int="-22" con="-23" dex="0" wit="-5" men="21" hp="344.113" mp="151.206" cp="172.0565" />
				<level val="20" bonus="1.09" hp_regen="3.4" mp_regen="1.2" cp_regen="2.5" str="-41" int="-20" con="-20" dex="1" wit="0" men="22" hp="359.7" mp="158.4" cp="179.85" />
				<level val="21" bonus="1.1" hp_regen="3.5" mp_regen="1.5" cp_regen="3.5" str="-39" int="-19" con="-18" dex="1" wit="5" men="23" hp="396.0" mp="169.29" cp="198.0" />
				<level val="22" bonus="1.11" hp_regen="3.6" mp_regen="1.5" cp_regen="3.5" str="-37" int="-17" con="-15" dex="2" wit="10" men="25" hp="432.63" mp="180.279" cp="216.315" />
				<level val="23" bonus="1.12" hp_regen="3.7" mp_regen="1.5" cp_regen="3.5" str="-34" int="-15" con="-13" dex="3" wit="16" men="26" hp="469.59" mp="191.367" cp="234.795" />
				<level val="24" bonus="1.13" hp_regen="3.8" mp_regen="1.5" cp_regen="3.5" str="-32" int="-14" con="-10" dex="4" wit="22" men="27" hp="506.88" mp="202.554" cp="253.44" />
				<level val="25" bonus="1.14" hp_regen="3.9" mp_regen="1.5" cp_regen="3.5" str="-29" int="-12" con="-7" dex="5" wit="28" men="28" hp="544.5" mp="213.84" cp="272.25" />
				<level val="26" bonus="1.15" hp_regen="4.0" mp_regen="1.5" cp_regen="3.5" str="-27" int="-10" con="-5" dex="6" wit="34" men="30" hp="582.45" mp="225.225" cp="291.225" />
				<level val="27" bonus="1.16" hp_regen="4.1" mp_regen="1.5" cp_regen="3.5" str="-24" int="-8" con="-2" dex="7" wit="41" men="31" hp="620.73" mp="236.709" cp="310.365" />
				<level val="28" bonus="1.17" hp_regen="4.2" mp_regen="1.5" cp_regen="3.5" str="-22" int="-6" con="1" dex="8" wit="48" men="32" hp="659.34" mp="248.292" cp="329.67" />
				<level val="29" bonus="1.18" hp_regen="4.3" mp_regen="1.5" cp_regen="3.5" str="-19" int="-5" con="4" dex="9" wit="55" men="34" hp="698.28" mp="259.974" cp="349.14" />
				<level val="30" bonus="1.19" hp_regen="4.4" mp_regen="1.5" cp_regen="3.5" str="-16" int="-3" con="7" dex="10" wit="63" men="35" hp="737.55" mp="271.755" cp="368.775" />
				<level val="31" bonus="1.2" hp_regen="4.5" mp_regen="1.8" cp_regen="4.5" str="-13" int="-1" con="10" dex="11" wit="71" men="36" hp="777.15" mp="283.635" cp="388.575" />
				<level val="32" bonus="1.21" hp_regen="4.6" mp_regen="1.8" cp_regen="4.5" str="-10" int="1" con="14" dex="12" wit="80" men="38" hp="817.08" mp="295.614" cp="408.54" />
				<level val="33" bonus="1.22" hp_regen="4.7" mp_regen="1.8" cp_regen="4.5" str="-6" int="3" con="17" dex="13" wit="89" men="39" hp="857.34" mp="307.692" cp="428.67" />
				<level val="34" bonus="1.23" hp_regen="4.8" mp_regen="1.8" cp_regen="4.5" str="-3" int="5" con="21" dex="14" wit="98" men="40" hp="897.93" mp="319.869" cp="448.965" />
				<level val="35" bonus="1.24" hp_regen="4.9" mp_regen="1.8" cp_regen="4.5" str="1" int="7" con="24" dex="15" wit="108" men="42" hp="938.85" mp="332.145" cp="469.425" />
				<level val="36" bonus="1.25" hp_regen="5.0" mp_regen="1.8" cp_regen="4.5" str="4" int="10" con="28" dex="16" wit="118" men="43" hp="980.1" mp="344.52" cp="490.05" />
				<level val="37" bonus="1.26" hp_regen="5.1" mp_regen="1.8" cp_regen="4.5" str="8" int="12" con="32" dex="17" wit="129" men="45" hp="1021.68" mp="356.994" cp="510.84" />
				<level val="38" bonus="1.27" hp_regen="5.2" mp_regen="1.8" cp_regen="4.5" str="12" int="14" con="36" dex="18" wit="141" men="46" hp="1063.59" mp="369.567" cp="531.795" />
				<level val="39" bonus="1.28" hp_regen="5.3" mp_regen="1.8" cp_regen="4.5" str="16" int="16" con="40" dex="19" wit="153" men="48" hp="1105.83" mp="382.239" cp="552.915" />
				<level val="40" bonus="1.29" hp_regen="5.4" mp_regen="1.8" cp_regen="4.5" str="20" int="19" con="44" dex="20" wit="165" men="49" hp="1148.4" mp="395.01" cp="574.2" />
				<level val="41" bonus="1.3" hp_regen="5.5" mp_regen="2.1" cp_regen="5.5" str="24" int="21" con="48" dex="21" wit="179" men="50" hp="1202.74" mp="416.46" cp="601.37" />
				<level val="42" bonus="1.31" hp_regen="5.6" mp_regen="2.1" cp_regen="5.5" str="29" int="23" con="53" dex="22" wit="193" men="52" hp="1257.498" mp="438.075" cp="628.749" />
				<level val="43" bonus="1.32" hp_regen="5.7" mp_regen="2.1" cp_regen="5.5" str="33" int="26" con="58" dex="24" wit="207" men="53" hp="1312.674" mp="459.855" cp="656.337" />
				<level val="44" bonus="1.33" hp_regen="5.8" mp_regen="2.1" cp_regen="5.5" str="38" int="28" con="62" dex="25" wit="223" men="55" hp="1368.268" mp="481.8" cp="684.134" />
